NTR: improve README with instructions and best practices
basecom/FixturesPlugin pull request #2
Opened 2022-07-26 15:52 UTC by boxblinkracer

review notes

I've added some visual concepts to the readme, like code snippets and paragraphs

also, i figured out some kind of best practice for plugin development.
used it in a plugin of mine.
could you verify it? the benefit is to avoid fixtures from being accidentally loaded when the plugin only has production dependencies :)

2022-07-26 20:26 UTC, jkniest commented on README.md
> +```
Only if they are using Auto Wiring. I think I would keep the example, but also mention that we have Auto Wiring configured.

2022-07-26 20:39 UTC, boxblinkracer commented on README.md
> +```
yeah, didnt work for me today, it probably wasnt turned on.
ill update the text :)

2022-07-26 20:53 UTC, boxblinkracer commented on README.md
> +```
text angepasst :)

2022-07-26 20:54 UTC, boxblinkracer commented on README.md
> +When you want to add fixtures to a plugin that you build, you might not want to deliver these fixtures in a production version of your plugin.
bitte das noch prüfen @jdambacher  @jkniest , was ihr davon haltet.
hat soweit gut ausgesehen bei mir....aber wäre toll wenn ihr das noch verifiziert, danke

2022-07-27 13:36 UTC, jkniest requested changes

2022-07-27 13:36 UTC, jkniest commented on README.md
> +If you're not using autowiring, then pelase register your fixtures with the tag `basecom.fixture`.
```suggestion
If you're not using autowiring, then please register your fixtures with the tag `basecom.fixture`.
```

2022-07-27 13:37 UTC, jkniest commented on README.md
> +When you want to add fixtures to a plugin that you build, you might not want to deliver these fixtures in a production version of your plugin.
Für mich hört sich das gut an ✌️

2022-07-27 20:07 UTC, jdambacher approved these changes

2022-07-27 20:08 UTC, merged